### ISSUE TITLE
Bug in exception handling code of ONProcess

### ISSUE THREAD

**Issue by philipstarkey** [varunsrin/one-py#1]
Hi,

I found a bug in the exception handling of [`ONProcess`](https://github.com/varunsrin/one-py/blob/master/onepy/onmanager.py#L31). On line 31 of onepy/onmanager.py you attempt to join a string and an int with a `+` which you can't do! It should be a comma instead (or typecast the int to a string)

So `print("error starting onenote " + version)` should become one of
- `print("error starting onenote " + str(version))`
- `print("error starting onenote", version)` (note the deleted space!)

Cheers,

**Comment by varunsrin** [comment]
Good catch! Feel free to submit a pull request, or I'll fix it myself later this weekend.
